// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

// Usuario

export const USUARIO_REGISTRO_START = 'USUARIO_REGISTRO_START';
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS';
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL';

export const USUARIO_EDITAR_START = 'USUARIO_EDITAR_START';
export const USUARIO_EDITAR_SUCCESS = 'USUARIO_EDITAR_SUCCESS';
export const USUARIO_EDITAR_FAIL = 'USUARIO_EDITAR_FAIL';

export const USUARIO_BAJA_START = 'USUARIO_BAJA_START';
export const USUARIO_BAJA_SUCCESS = 'USUARIO_BAJA_SUCCESS';
export const USUARIO_BAJA_FAIL = 'USUARIO_BAJA_FAIL';

// Rifa
export const REGISTRO_CREAR_START = 'REGISTRO_CREAR_START';
export const REGISTRO_CREAR_SUCCESS = 'REGISTRO_CREAR_SUCCESS';
export const REGISTRO_CREAR_FAIL = 'REGISTRO_CREAR_FAIL';

export const REGISTRO_CONSULTAR_START = 'REGISTRO_CONSULTAR_START';
export const REGISTRO_CONSULTAR_SUCCESS = 'REGISTRO_CONSULTAR_SUCCESS';
export const REGISTRO_CONSULTAR_FAIL = 'REGISTRO_CONSULTAR_FAIL';

export const REGISTRO_EDITAR_START = 'REGISTRO_EDITAR_START';
export const REGISTRO_EDITAR_SUCCESS = 'REGISTRO_EDITAR_SUCCESS';
export const REGISTRO_EDITAR_FAIL = 'REGISTRO_EDITAR_FAIL';

export const REGISTRO_ELIMINAR_START = 'REGISTRO_ELIMINAR_START';
export const REGISTRO_ELIMINAR_SUCCESS = 'REGISTRO_ELIMINAR_SUCCESS';
export const REGISTRO_ELIMINAR_FAIL = 'REGISTRO_ELIMINAR_FAIL';

